-- SILVER_AP_INVOICES proof query — rerun after every pipeline change
SELECT
  SOURCE_SYSTEM,
  COUNT(*)                        AS ROW_COUNT,
  COUNT(DISTINCT VENDOR_NAME)     AS VENDORS,
  SUM(INVOICE_AMOUNT)             AS TOTAL_AMOUNT,
  COUNT_IF(APPROVAL_STATUS = 'PENDING') AS PENDING,
  MIN(INVOICE_DATE)               AS EARLIEST_INVOICE,
  MAX(INVOICE_DATE)               AS LATEST_INVOICE
FROM COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
GROUP BY SOURCE_SYSTEM
ORDER BY SOURCE_SYSTEM;